# Generated by Django 2.1.4 on 2018-12-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_site_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='private_image',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Thumbnail of uploaded image'),
        ),
        migrations.AddField(
            model_name='public_image',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Thumbnail of uploaded image'),
        ),
    ]
